server.port=8085// cambiar por el puerto que tengo yo MS-STOCK --- IGNORE ---

spring.application.name=ms-stock





spring.datasource.url=jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=C:\Users\Usuario\Downloads\Wallet_MMG8HVEWK688YRH4
spring.datasource.username=SCHEMA_CATEGORIAS
spring.datasource.password=FullStack-Bodega1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

